import Head from 'next/head';
import { Box } from '@chakra-ui/react';
import { Form } from '../components/Form';
import { Blur } from '../components/Blur';

export default function Home() {
    return (
        <>
            <Head>
                <title>Hireable applicants</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box position="relative">
                <Form />
                <Blur
                    position="absolute"
                    top={-10}
                    left={-10}
                    style={{ filter: 'blur(70px)' }}
                />
            </Box>
        </>
    );
}
